Potentially interesting modifications to FibbingNode-+
Fibbing/FibbingNode pull request #4
Opened 2016-11-14 09:14 UTC by lferran

2016-11-15 01:44 UTC, oliviertilmans requested changes

2016-11-15 01:44 UTC, oliviertilmans commented on .gitmodules
> +	url = https://github.com/lferran/Quagga.git
This is something we cannot merge

2016-11-15 01:44 UTC, oliviertilmans commented on fibbingnode/misc/mininetlib/ipnet.py
> +                 ipBase='192.0.0.0/8',
Changing that default looks hazardous as 192/8 is part of the public space

2016-11-15 01:44 UTC, oliviertilmans commented on fibbingnode/misc/mininetlib/ipnet.py
> +            cmd = "iptables -A INPUT -s {0} -p udp -j DROP".format(self.ipBase)
What is the use case for dropping UDP traffic ?

2016-11-15 01:44 UTC, oliviertilmans commented on fibbingnode/misc/mininetlib/ipnet.py
> +            props[itf.name] = {
Why is that change needed ? It prevents from accessing link information easily, e.g. db[a][b][ip] to know the ip address of a towards b.

2016-11-15 01:44 UTC, oliviertilmans commented on fibbingnode/misc/router.py
> +from fibte import counterCollector_path, ifDescrNamespace_path, tmp_files
This set of changes should not be here as they depend on some external lib

2016-11-15 01:44 UTC, oliviertilmans commented on fibbingnode/res/default.cfg
> +hello_interval=20
This will slow down _a lot_ the convergence time at bootstrap, which is not something we want for quick experiments

2016-11-15 01:44 UTC, oliviertilmans commented on fibbingnode/southbound/fibbing.py
> +        if self.routes:
This change would be super useful!
Could you try to:
* Limit the route removal to only the ones that were advertized by the application.
* Perform that removal when an application disconnects

2016-11-15 01:44 UTC, oliviertilmans commented on fibbingnode/southbound/lsdb.py
> +            cosmmit = False
This looks like a typo to me

2016-11-15 01:45 UTC, oliviertilmans commented
Could you try to address the comments and then rebase to get a cleaner history?
Thanks!

2016-11-15 08:21 UTC, lferran commented on fibbingnode/misc/mininetlib/ipnet.py
> +            cmd = "iptables -A INPUT -s {0} -p udp -j DROP".format(self.ipBase)
This is just a black hole (ie consumer) at the Mininet hosts, useful for the creation of UDP flows in the network.

Sorry, this shouldn't be here, but in the TE code instead. :+1:

2016-11-15 08:23 UTC, lferran commented on .gitmodules
> +	url = https://github.com/lferran/Quagga.git
True. I wanted to select specific commits for the pull request, and obviously leave this one out.. but I didn't find how.

2016-11-15 08:23 UTC, lferran commented on fibbingnode/misc/mininetlib/ipnet.py
> +                 ipBase='192.0.0.0/8',
:+1: 
When I was creating a fat-tree topology with k > 4, the IPNet constructor was running out of broadcast domains... and this was just a quick fix when attempting to solve the problem.

What would be the best way to have more addresses? increasing the max prefix len?

2016-11-15 08:42 UTC, lferran commented on fibbingnode/southbound/lsdb.py
> +            cosmmit = False
yep ;)

2016-11-15 10:29 UTC, lferran commented
ok! that's what I did:

- Created a new branch new-fibbing-features
- Checked out to the new branch
- Revert all the commits done so far (so it looks exactly like upstream, in this case: Fibbing/FibbingNode)
- Then I cherry-picked some of the useful commits from the previous pull request!

I will finish addressing all the comments you told me, and then we could just create another pull-request from the new branch.

From now on, I will use this branch to change stuff that could be interesting to you. And keep weird fixes in my master for now...

What do you think? Please let me know if you think I could organize it in a better way.

2016-11-15 11:28 UTC, oliviertilmans commented
This is indeed a much cleaner way to handle this !

2016-11-19 14:16 UTC, oliviertilmans commented
Closing as per #5

2016-11-19 14:16 UTC, closed without merging